### PR TITLE
Update EventPanel Timeline view

### PR DESCRIPTION
**Pull request by olegbaturin**

### CODE REVIEW

**Comment by samdark** [comment]
@olegbaturin what does it do?

**Comment by olegbaturin** [comment]
> @olegbaturin what does it do?

This aligns events timeline to the left.

image

**Review by vjik — COMMENTED** [review]
Can it implemented as HTML classes with CSS in separate files?

**Comment by olegbaturin** [comment]
> Can it implemented as HTML classes with CSS in separate files?

no

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
